import mongoose,{Schema} from "mongoose"
const userSchema=new Schema(
    {   profilepicture:
        {
            type:String,//cloudinary url
            required:true
        },
        fullname:{
            type:String,
            required:true,
            trim:true,
            index:true
        },
        email:{
            type:String,
            required:true,
            unique:true,
            lowercase:true,
            trim:true
        },
        password:{
            type:String,
            required:true,
        },
        phoneNumber:{
            type:String,
            unique:true,
        },
        gradutationYear:{
            type:String,
            trim:true,
            index:true,
            required:true
        },
        department:{
            type:String,
            trim:true,
            index:true,
            required:true
        },
        enrollmentNumber:{
            type:String,
            unique:true,
            trim:true,
            required:true,
        },
        currentCompany:{
        type:String,
        },
        jobTitle:{
            type:String,
        },
        location:{
            type:String,
        },
        linkedinUrl:{
            type:String,
            unique:true,
            required:true
        },
        role:{
            type:String,
            enum:["alumni","admin"],
            default:"alumni"
        },
        refreshToken:{
            type:String,
        }
    },
     {
        timestamps:true
    })    
export const User=mongoose.model("User",userSchema)